import type { Post } from '../../types';

/** Serialize merged posts into a committed, type-checked TS module. */
export function serializeGenerated(posts: Record<string, Post>, order: string[]): string {
  return (
    `// AUTO-GENERATED by scripts/build-posts.ts — do not edit by hand.\n` +
    `import type { Post } from '../types';\n\n` +
    `export const GENERATED_POSTS: Record<string, Post> = ${JSON.stringify(posts, null, 2)};\n\n` +
    `export const GENERATED_ORDER: string[] = ${JSON.stringify(order, null, 2)};\n`
  );
}
