// AUTO-GENERATED by scripts/build-posts.ts — do not edit by hand.
import type { Post } from '../types';

export const GENERATED_POSTS: Record<string, Post> = {};

export const GENERATED_ORDER: string[] = [];
